const projectData={
  school:{category:"Education · Executed 2024",title:"Sustainable 12-Class Girls' School",meta:"Bushehr, Iran · Site 5,000 m² · GFA 3,000 m² · 3 floors",image:"/api/proxy?path=/assets/sustainable-school.jpg",description:"A climate-responsive school organized around a shaded social courtyard. Orientation-specific facades, deep reveals, passive ventilation and Shanasheel-inspired screens support comfort, identity and future phased development.",tags:["Climate-responsive design","Central courtyard","Passive shading","Executed project"]},
  sports:{category:"Sport + Wellness",title:"Bushehr Multifunctional Sports Complex",meta:"Site 9,400 m² · GFA 6,500 m²",image:"/api/proxy?path=/assets/sports-complex.png",description:"A multifunctional sports, wellness and community complex that reinterprets Bushehr's vernacular Shanasheel as a contemporary louvered environmental envelope, combining shade, airflow, daylight control and civic identity.",tags:["Spatial planning","Climate resilience","Multi-use","Vernacular reinterpretation"]},
  coastal:{category:"Coastal Master Plan",title:"Sustainable Coastal Beach Pavilion",meta:"Bushehr, Iran · 1.2-hectare waterfront",image:"/api/proxy?path=/assets/coastal-masterplan.jpg",description:"A waterfront master plan translating the environmental intelligence of Bushehr's Shanasheel into a contemporary public realm. Porous planning, shaded thresholds, saline-resistant materials and cross-ventilation support a resilient coastal destination.",tags:["Master plan","Public realm","Passive cooling","Coastal resilience"]},
  "gas-office":{category:"Office",title:"Sustainable Office Building for a Gas Company",meta:"Genaveh, Bushehr · GFA 1,400 m² · 3 floors",image:"/api/proxy?path=/assets/gas-office.jpg",description:"A perforated double-layer facade decodes the passive logic of the traditional Shanasheel. The patterned screen guides breezes, shades glazing, filters daylight and protects privacy while establishing a contemporary local identity.",tags:["Shanasheel","Passive facade","Workplace","Sustainable architecture"]},
  "industrial-hq":{category:"Industrial Workplace · 2024",title:"Five-Storey Administrative Headquarters",meta:"Bushehr · GFA 3,000 m² · 30-seat conference hall",image:"/api/proxy?path=/assets/industrial-hq.jpg",description:"A multi-level headquarters for an industrial environment. Its executive conference hall uses an integrated central display and oval table to create equal sightlines, clear communication and focused decision-making.",tags:["Industrial context","Executive workplace","Interior design","Integrated display"]},
  "admin-residential":{category:"Mixed Use",title:"Administrative + Residential Building",meta:"Bushehr · 3 floors",image:"/api/proxy?path=/assets/admin-residential.jpg",description:"A compact administrative and residential building developed through conceptual, basic and detailed design. The facade combines flexible planning with climate-aware shading and patterned screens.",tags:["Flexible planning","Energy optimization","Mixed use"]},
  administrative:{category:"Workplace",title:"Administrative Building",meta:"GFA 1,200 m² · Landscape 3,000 m² · 3 floors",image:"/api/proxy?path=/assets/administrative.jpg",description:"A three-storey workplace with modular planning, integrated services and shaded exterior articulation, balancing operational clarity with local material expression.",tags:["Structural flexibility","Climate facade","Local materiality"]},
  residence:{category:"Residential",title:"Vernacular-Inspired Residential Building",meta:"Bushehr · 2 floors · 200 m²",image:"/api/proxy?path=/assets/vernacular-residence.jpg",description:"A residential reinterpretation of Bushehr's shaded galleries, perforated screens and deep thresholds, using passive cooling logic and landscape to moderate the hot-humid microclimate.",tags:["Vernacular architecture","Passive cooling","Thermal envelope"]},
  housing:{category:"Residential Planning",title:"Staff Housing at Settlement Scale",meta:"Alishahr · 240-unit complex and 150-unit complex",image:"/api/proxy?path=/assets/staff-housing-240.jpg",description:"Large residential developments organized around landscaped communal spaces, with coordinated unit planning, facade articulation and interior studies at settlement scale.",tags:["Residential planning","Community space","Facade development"]},
  document:{category:"Institutional",title:"International-Standard Document Center",meta:"GFA 5,000 m²",image:"/api/proxy?path=/assets/document-center.jpg",description:"An administrative document center organized around a clear entrance sequence, shaded facade elements and climate-aware massing, integrating formal identity with operational planning and conference functions.",tags:["Administrative facility","Integrated planning","Climate facade"]},
  forest:{category:"Landscape + Urbanism",title:"120-Hectare Forest Park Master Plan",meta:"Large-scale landscape and recreational planning",image:"/api/proxy?path=/assets/forest-park.jpg",description:"A forest park structured by primary axes, linked garden rooms and a hierarchy of movement. The plan balances formal orientation with distributed recreation, planting and public gathering zones.",tags:["Landscape planning","Public space","Large-scale design"]},
  "bus-stop":{category:"Urban Furniture",title:"Bus Stop Station",meta:"Bushehr · 20 m²",image:"/api/proxy?path=/assets/bus-stop.jpg",description:"A compact urban shelter combining a contemporary enclosure, passenger comfort and references to Bushehr's craft and climatic traditions.",tags:["Urban furniture","Mobility","Climate comfort"]},
  landmarks:{category:"Industrial Identity",title:"Industrial Site Entrance Landmarks",meta:"Large-scale sculptural gateway alternatives",image:"/api/proxy?path=/assets/industrial-landmarks.jpg",description:"Landmark studies for visibility, identity and safe perception from heavy-vehicle approach routes, translating industrial movement into a memorable gateway.",tags:["Landmark design","Industrial identity","Gateway"]}
};

const filters=document.querySelectorAll('.filter');
const cards=document.querySelectorAll('.project-card');
filters.forEach(button=>button.addEventListener('click',()=>{
  filters.forEach(item=>{item.classList.remove('is-active');item.setAttribute('aria-pressed','false')});
  button.classList.add('is-active');button.setAttribute('aria-pressed','true');
  const value=button.dataset.filter;
  cards.forEach(card=>card.hidden=value!=='all'&&!card.dataset.category.split(' ').includes(value));
}));

const dialog=document.querySelector('#project-dialog');
const dialogMedia=dialog.querySelector('.dialog-media');
function openProject(key){const p=projectData[key];if(!p)return;dialogMedia.innerHTML=`<img src="${p.image}" alt="${p.title}">`;dialog.querySelector('.dialog-category').textContent=p.category;dialog.querySelector('.dialog-title').textContent=p.title;dialog.querySelector('.dialog-meta').textContent=p.meta;dialog.querySelector('.dialog-description').textContent=p.description;dialog.querySelector('.dialog-tags').innerHTML=p.tags.map(tag=>`<span>${tag}</span>`).join('');dialog.showModal();}
cards.forEach(card=>{card.addEventListener('click',()=>openProject(card.dataset.project));card.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();openProject(card.dataset.project)}})});
dialog.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()});

const menuButton=document.querySelector('.menu-toggle');
const nav=document.querySelector('#main-nav');
menuButton.addEventListener('click',()=>{const open=nav.classList.toggle('is-open');menuButton.setAttribute('aria-expanded',String(open))});
nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('is-open');menuButton.setAttribute('aria-expanded','false')}));
